const { SlashCommandBuilder } = require('discord.js');

const Logger = require('../utils/logger');
const {handleReportCommand} = require("../common/report");

module.exports = {
    data: new SlashCommandBuilder()
        .setName('report')
        .setDescription('Share a report using the code generated by the GrepoData userscript.')
        .addStringOption(option =>
            option
                .setName('hash')
                .setDescription(`Paste the report hash generated by the userscript. For example: 'r219625881' or 'rm816615899'`)
                .setRequired(true)),
    async execute(interaction) {
        try {
            await handleReportCommand(interaction)
        } catch (e) {
            Logger.error(e.stack)
        }
    },
};
